from flask import request, current_app, url_for, render_template, abort
from pygments.lexers import get_all_lexers, get_lexer_by_name
from app.views import BaseView
import app.repositories.paste as paste

blacklist = [
    'ActionScript',
    'ABAP',
    'APL',
    'ABNF',
    'ActionScript 3',
    'ADL',
    'Agda',
    'Aheui',
    'Alloy',
    'AmbientTalk',
    'Ampl',
    'HTML + Angular2',
    'Angular2',
    'ANTLR With ActionScript Target',
    'ANTLR With C# Target',
    'ANTLR With CPP Target',
    'ANTLR With Java Target',
    'ANTLR',
    'ANTLR With ObjectiveC Target',
    'ANTLR With Perl Target',
    'ANTLR With Python Target',
    'ANTLR With Ruby Target',
    'AspectJ',
    'Asymptote',
    'Augeas',
    'AutoIt',
    'BBC Basic',
    'BBCode',
    'BC',
    'Base Makefile',
    'Bash Session',
    'Befunge',
    'BibTeX',
    'BlitzBasic',
    'BlitzMax',
    'BNF',
    'Boa',
    'Boo',
    'Boogie',
    'Bro',
    'BUGS',
    'BST',
    'brainfuck',
    'CAmkES',
    'c-objdump',
    'CPSA',
    'ca65 assembler',
    'cADL',
    'CapDL',
    'Cap\'n Proto',
    'CBM BASIC V2',
    'Ceylon',
    'CFEngine3',
    'ChaiScript',
    'Chapel',
    'Charmci',
    'HTML+Cheetah',
    'JavaScript+Cheetah',
    'Cheetah',
    'XML+Cheetah',
    'Cirru',
    'Clay',
    'Clean',
    'COBOLFree',
    'Coldfusion CFC',
    'Coldfusion HTML',
    'cfstatement',
    'Component Pascal',
    'Coq',
    'cpp-objdump',
    'Crmsh',
    'Croc',
    'Cryptol',
    'Csound Document',
    'Csound Orchestra',
    'Csound Score',
    'CSS+Django/Jinja',
    'CSS+Ruby',
    'CSS+Genshi Text',
    'CSS+PHP',
    'CSS+Smarty',
    'CUDA',
    'Cypher',
    'd-objdump',
    'Darcs Patch',
    'DASM16',
    'Debian Control file',
    'Debian Sourcelist',
    'Delphi',
    'dg',
    'Diff',
    'DTD',
    'Duel',
    'Dylan session',
    'Dylan',
    'DylanLID',
    'ECL',
    'eC',
    'Earl Grey',
    'Easytrieve',
    'EBNF',
    'Eiffel',
    'Eiffel',
    'Elixir iex session',
    'Erlang erl session',
    'HTML+Evoque',
    'Evoque',
    'XML+Evoque',
    'Ezhil',
    'Factor',
    'Fancy',
    'Fantom',
    'Felix',
    'Fennel',
    'Flatline',
    'FloScript',
    'FortranFixed',
    'FoxPro',
    'Freefem',
    'GAP',
    'GLSL',
    'GAS',
    'Genshi Text',
    'Gettext Catalog',
    'Gherkin',
    'Gnuplot',
    'Golo',
    'GoodData-CL',
    'Gosu',
    'Gosu Template',
    'Groff',
    'HLSL',
    'HTML+Handlebars',
    'Haxe',
    'Hexdump',
    'HSAIL',
    'Hspec',
    'HTML+Genshi',
    'Hxml',
    'Hy',
    'Hybris',
    'IDL',
    'Icon',
    'Idris',
    'Igor',
    'Inform 6',
    'Inform 6 template',
    'Inform 7',
    'Io',
    'Ioke',
    'IRC logs',
    'Isabelle',
    'J',
    'JAGS',
    'Jasmin',
    'JavaScript+Django/Jinja',
    'JavaScript+Ruby',
    'JavaScript+Genshi Text',
    'JavaScript+PHP',
    'JavaScript+Smarty',
    'JCL',
    'JSGF',
    'JSONBareObject',
    'JSON-LD',
    'Julia',
    'Julia console',
    'Juttle',
    'Kal',
    'Kconfig',
    'Koka',
    'LSL',
    'CSS+Lasso',
    'HTML+Lasso',
    'JavaScript+Lasso',
    'Lasso',
    'XML+Lasso',
    'Lean',
    'Limbo',
    'Literate Agda',
    'Literate Cryptol',
    'Literate Haskell',
    'Literate Idris',
    'LiveScript',
    'Logos',
    'Logtalk',
    'MOOCode',
    'MSDOS Session',
    'CSS+Mako',
    'HTML+Mako',
    'Mako',
    'JavaScript+Mako',
    'XML+Mako',
    'MAQL',
    'Mask',
    'Mason',
    'Mathematica',
    'Matlab',
    'Matlab session',
    'MiniD',
    'Modelica',
    'Modula-2',
    'MoinMoin/Trac Wiki markup',
    'Monkey',
    'Monte',
    'mozpercentpreproc',
    'CSS+mozpreproc',
    'mozhashpreproc',
    'Javascript+mozpreproc',
    'XUL+mozpreproc',
    'MQL',
    'Mscgen',
    'Mscgen',
    'MuPAD',
    'MXML',
    'MySQL',
    'CSS+Myghty',
    'HTML+Myghty',
    'JavaScript+Myghty',
    'Myghty',
    'XML+Myghty',
    'NCL',
    'NSIS',
    'objdump-nasm',
    'Nemerle',
    'nesC',
    'Newspeak',
    'Nginx configuration file',
    'Nit',
    'NuSMV',
    'objdump',
    'Octave',
    'ODIN',
    'Ooc',
    'Opa',
    'OpenEdge ABL',
    'PacmanConf',
    'PkgConfig',
    'Pan',
    'ParaSail',
    'Pawn',
    'Pig',
    'Pike',
    'Pony',
    'PostScript',
    'PL/pgSQL',
    'PostgreSQL SQL dialect',
    'PostgreSQL console (psql)',
    'POVRay',
    'PowerShell Session',
    'Praat',
    'Properties',
    'PyPy Log',
    'Python 3',
    'Python 3.0 Traceback',
    'Python console session',
    'Python Traceback',
    'QVTO',
    'RConsole',
    'Relax-NG Compact',
    'RPMSpec',
    'Ragel in C Host',
    'Ragel in CPP Host',
    'Ragel in D Host',
    'Embedded Ragel',
    'Ragel in Java Host',
    'Ragel',
    'Ragel in Objective C Host',
    'Ragel in Ruby Host',
    'Raw token data',
    'Rd',
    'REBOL',
    'Red',
    'Redcode',
    'ResourceBundle',
    'Rexx',
    'RHTML',
    'Roboconf Graph',
    'Roboconf Instances',
    'RobotFramework',
    'RQL',
    'RSL',
    'TrafficScript',
    'Ruby irb session',
    'SAS',
    'S',
    'Standard ML',
    'SARL',
    'Scaml',
    'Shen',
    'Silver',
    'Slash',
    'Slurm',
    'Smali',
    'SmartGameFormat',
    'Snobol',
    'Snowball',
    'SourcePawn',
    'SPARQL',
    'sqlite3con',
    'SquidConf',
    'Scalate Server Page',
    'Stan',
    'Stata',
    'SuperCollider',
    'SWIG',
    'systemverilog',
    'TAP',
    'TADS 3',
    'Tcsh Session',
    'Tea',
    'Tera Term macro',
    'Termcap',
    'Terraform',
    'Thrift',
    'Transact-SQL',
    'Treetop',
    'Turtle',
    'HTML+Twig',
    'TypoScriptCssData',
    'TypoScriptHtmlData',
    'TypoScript',
    'ucode',
    'Unicon',
    'UrbiScript',
    'VCL',
    'VCLSnippets',
    'VCTreeStatus',
    'VGL',
    'HTML+Velocity',
    'Velocity',
    'XML+Velocity',
    'verilog',
    'vhdl',
    'VimL',
    'WDiff',
    'Whiley',
    'X10',
    'XML+Django/Jinja',
    'XML+Ruby',
    'XML+PHP',
    'XML+Smarty',
    'XSLT',
    'Xtend',
    'xtlang',
    'YAML+Jinja',
    'Zephir',
    'HTML+Mako',
    'XML+Mako',
    'JavaScript+Mako',
    'CSS+Mako'
]


class EditView(BaseView):
    methods = ['GET', 'POST']

    def __init__(self):
        super().__init__()
        self.languages = sorted(
            [{
                'name': lexer[0],
                'alias': lexer[1][0]
            } for lexer in get_all_lexers() if lexer[0] not in blacklist],
            key=lambda i: i['name'].upper()
        )

    def dispatch_request(self):
        if request.method == 'POST':
            maxlength = current_app.config.get('MAX_PASTE_LENGTH')
            text = request.form.get('text')
            alias = request.form.get('alias')

            if text is None or text.strip() == '':
                abort(400)
            elif maxlength is not None and len(text) > maxlength:
                abort(413)

            hexhash = paste.insert_paste(text)
            if alias:
                lexer = get_lexer_by_name(alias)
                extension = lexer.filenames[0][2:]
                url = url_for(
                    'paste.view.extension',
                    hexhash=hexhash,
                    extension=extension,
                    _external=True
                )
            else:
                url = url_for('paste.view', hexhash=hexhash, _external=True)
            return self.redirect_or_text(url, 200)

        text, _ = paste.get_paste(request.args.get('clone'))
        return render_template(
            'index.html',
            text=text,
            languages=self.languages,
            disabled=['clone', 'new', 'raw', 'download']
        )
